### ISSUE TITLE
[not confirmed] `AttributeError` related to BackPACK's IO

### ISSUE THREAD

**Issue by littleolex** [f-dangel/backpack#212] opened 2021-08-07 10:02 UTC
AttributeError: 'Conv2d' object has no attribute 'input0'

**Comment by f-dangel** [comment] 2021-08-07 10:07
Hi, thanks for reaching out.

Could you provide more details how you obtained this error?
For instance, a small code snippet that reproduces the issue.

Best

**Comment by littleolex** [comment] 2021-08-07 10:15
![image](https://user-images.githubusercontent.com/39018555/128596832-d7f90ce1-4908-426d-9b1a-8b5a79d87421.png)

**Comment by littleolex** [comment] 2021-08-07 10:15
I use torch 1.8.0

**Comment by f-dangel** [comment] 2021-08-07 10:34
The error is caused by one of BackPACK's extensions that tries to access information stored from a forward pass. From the traceback you posted, it is clear where the problem occurs. But to track down the issue, a functioning piece of code that runs into exactly this error will be possible.

**Comment by littleolex** [comment] 2021-08-07 10:52
I want to ask a question , if the loss of a example must calculate with the whole batch , then the model outputs a loss ,which is  a tensor whose size is the batchsize , that means loss[0] is the loss of the first example , then can I still use your method to get the individual gradient ?

**Comment by f-dangel** [comment] 2021-08-08 12:31
If you want to compute gradients for `loss[0]`, `loss[1]`, `...` in parallel, try
```python

# ... extend the model, do a forward pass -> loss

# compute the gradients of `loss[0], loss[1], ...`
with backpack(BatchGrad()):
    # loss has shape [N]
    loss.sum(0).backward()
```

**Comment by littleolex** [comment] 2021-08-08 12:41
then ,how can I get the individual gradient , still same with the tutorial? Another a question is I didn't find to function to replace the BatchNorm layer , but I heard it really exits, can you tell me how to do it ?

**Comment by littleolex** [comment] 2021-08-11 13:58
I find a strange thing,When I use you optimizer to update param , even when I didn't clip gradient and add noise , I can not reach the same accuracy as original optimizer.

**Comment by littleolex** [comment] 2021-08-11 14:05
scaling_factors = torch.clamp_max(l2_norms / C, 1.0)
clipped_grads = p.grad_batch * make_broadcastable(scaling_factors, p.grad_batch)
 these two sentences shows :if the gradient'norm < C，then the gradient will multiply with a number which is smaller than 1.That seems wrong.

**Comment by schaefertim** [comment] 2021-08-19 08:46
Hi,
I am also working on BackPACK and I'd like to help you. However, I have two difficulties:
- You asked many questions. I don't know which one to answer.
- I don't fully understand your questions. I probably need more information/code.

I suggest that you ask your open questions in this form:
1. How do I resolve this error: `YourError`?
    - error message
    - code that reproduces the error
    - maybe purpose of code
2. How can I compute the following?
    - description what you want to compute
    - what you tried

**Comment by littleolex** [comment] 2021-08-19 12:43
Thanks so much ,  but I have found another way to achieve gradient clipping.

**Comment by f-dangel** [comment] 2021-09-13 16:08
I will go ahead and close this.

**Closed by f-dangel** 2021-09-13 16:08 UTC
Labels: question, wontfix
